branch-defaults:
  master:
    environment: clickyclick
environment-defaults:
  clickyclick:
    branch: null
    repository: null
global:
  application_name: ClickyClick
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
